/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarket {
  export type MarketInfoStruct = {
    question: string;
    imageUrl: string;
    category: string;
    endTime: BigNumberish;
    totalYesPool: BigNumberish;
    totalNoPool: BigNumberish;
    state: BigNumberish;
    finalOutcome: BigNumberish;
  };

  export type MarketInfoStructOutput = [
    question: string,
    imageUrl: string,
    category: string,
    endTime: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint,
    state: bigint,
    finalOutcome: bigint
  ] & {
    question: string;
    imageUrl: string;
    category: string;
    endTime: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
    state: bigint;
    finalOutcome: bigint;
  };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyShares"
      | "cancelMarket"
      | "category"
      | "claimWinnings"
      | "collateralToken"
      | "endTime"
      | "factory"
      | "feePercentage"
      | "feeRecipient"
      | "finalOutcome"
      | "getMarketInfo"
      | "imageUrl"
      | "noShares"
      | "question"
      | "resolveMarket"
      | "resolver"
      | "state"
      | "totalNoPool"
      | "totalYesPool"
      | "yesShares"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCancelled"
      | "MarketResolved"
      | "SharesBought"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyShares",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "category", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "endTime", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalOutcome",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "imageUrl", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "noShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "question", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalNoPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalYesPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yesShares",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "category", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "imageUrl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "question", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalNoPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYesPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yesShares", data: BytesLike): Result;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [outcome: BigNumberish];
  export type OutputTuple = [outcome: bigint];
  export interface OutputObject {
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesBoughtEvent {
  export type InputTuple = [
    user: AddressLike,
    isYes: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, isYes: boolean, amount: bigint];
  export interface OutputObject {
    user: string;
    isYes: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, fee: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShares: TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelMarket: TypedContractMethod<[], [void], "nonpayable">;

  category: TypedContractMethod<[], [string], "view">;

  claimWinnings: TypedContractMethod<[], [void], "nonpayable">;

  collateralToken: TypedContractMethod<[], [string], "view">;

  endTime: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  feePercentage: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  finalOutcome: TypedContractMethod<[], [bigint], "view">;

  getMarketInfo: TypedContractMethod<
    [],
    [PredictionMarket.MarketInfoStructOutput],
    "view"
  >;

  imageUrl: TypedContractMethod<[], [string], "view">;

  noShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  question: TypedContractMethod<[], [string], "view">;

  resolveMarket: TypedContractMethod<
    [_outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolver: TypedContractMethod<[], [string], "view">;

  state: TypedContractMethod<[], [bigint], "view">;

  totalNoPool: TypedContractMethod<[], [bigint], "view">;

  totalYesPool: TypedContractMethod<[], [bigint], "view">;

  yesShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [isYes: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "category"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "endTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalOutcome"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<[], [PredictionMarket.MarketInfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "imageUrl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "noShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "question"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<[_outcome: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalNoPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalYesPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yesShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "SharesBought"
  ): TypedContractEvent<
    SharesBoughtEvent.InputTuple,
    SharesBoughtEvent.OutputTuple,
    SharesBoughtEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "MarketCancelled()": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketResolved(uint8)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "SharesBought(address,bool,uint256)": TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;
    SharesBought: TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;

    "WinningsClaimed(address,uint256,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
